# docker-compose.atom.yaml
# docker compose -f docker-compose.atom.yaml up -d --build
# перезепуск nginx
# docker compose -f docker-compose.atom.yaml restart nginx_gateway
services:
  certbot_init:
    image: ghcr.io/alexanderjkochnev/certbot:latest
    container_name: certbot_init
    volumes:
      - certs_data:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    entrypoint: /bin/sh -c "
      if [ ! -f /etc/letsencrypt/live/abc8888.ru/fullchain.pem ]; then
      certbot certonly --standalone \
      --non-interactive --agree-tos --email admin@abc8888.ru \
      -d abc8888.ru -d api.abc8888.ru;
      else
      echo 'Certificates already exist';
      fi"
    ports:
      - "80:80"

  nginx_gateway:
    image: ghcr.io/alexanderjkochnev/nginx1.28.1:stable-alpine
    container_name: nginx_gateway
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/static:/etc/nginx/static:ro
      - certs_data:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    depends_on:
      certbot_init:
        condition: service_completed_successfully
    # Добавлен --post-hook для перезагрузки nginx внутри контейнера
    command: /bin/sh -c "echo '0 12 * * * certbot renew --webroot -w /var/www/certbot --post-hook \"nginx -s reload\"' > /etc/crontabs/root && crond && nginx -g 'daemon off;'"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
  
  wine_host:
    image: ghcr.io/alexanderjkochnev/postgres:17-alpine
    container_name: ${POSTGRES_HOST}
    restart: unless-stopped
    # Команда запуска с тюнингом под 64ГБ ОЗУ
    command: >
      postgres
      -c shared_buffers=16GB
      -c effective_cache_size=48GB
      -c maintenance_work_mem=2GB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c work_mem=128MB
      -c min_wal_size=1GB
      -c max_wal_size=4GB
      -c max_worker_processes=14
      -c max_parallel_workers_per_gather=4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "${POSTGRES_PORT}"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./pg_dump:/tmp
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '8'       # Разрешаем использовать до 8 ядер при нагрузке
          memory: 20G     # Лимит чуть выше shared_buffers + запас на процессы
        reservations:
          cpus: '2'
          memory: 16G

  mongo:
    image: ghcr.io/alexanderjkochnev/mongo:4.4.20
    container_name: ${MONGODB_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    expose:
      - "${MONGO_INN_PORT}"
    volumes:
      - ./mongodb_data:/data/db
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: >
      mongod
      --bind_ip_all
      --wiredTigerCacheSizeGB 4
      --storageEngine wiredTiger
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/admin --quiet -u admin -p admin
      interval: 15s
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G  # Mongo любит память

  app:
    build: .
    container_name: app
    restart: unless-stopped
    # Увеличиваем количество воркеров: (2 * ядра) + 1 для Xeon — это будет летать
    command: uvicorn app.main:app --host 0.0.0.0 --port ${API_PORT} --workers 9
    depends_on:
      wine_host:
        condition: service_healthy
      mongo:
        condition: service_healthy
    expose:
      - ${API_PORT}
    environment:
      # POSTGRES_HOST: ${POSTGRES_HOST}
      # MONGODB_URL: mongodb://admin:admin@mongo:${MONGO_INN_PORT}
      # NODE_ENV: production
      POSTGRES_HOST: ${POSTGRES_HOST}
      WEB_PORT: ${API_PORT}
      WEB_HOST: ${API_HOST}
      BASE_URL: ${BASE_URL}
      NODE_ENV: production
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G

  preact_front:
    build:
      context: ./preact_front
      dockerfile: Dockerfile
    container_name: preact_prod
    restart: unless-stopped
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

volumes:
  certs_data:
  certbot_www:
  pg_data:
  mongodb_data:

networks:
  default:
    name: web_network
